# Generated by Django 4.2.30 on 2026-06-25 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_unit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, verbose_name='ID периода')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Период подготовки',
                'verbose_name_plural': 'Периоды подготовки',
                'ordering': ('section', 'order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='TrainingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('variant', models.CharField(blank=True, choices=[('', 'Обычная таблица'), ('lesson-schedule', 'Сабактардын жүгүртмөсү')], default='', max_length=40, verbose_name='Тип таблицы')),
                ('columns', models.JSONField(default=list, verbose_name='Колонки')),
                ('rows', models.JSONField(blank=True, default=list, verbose_name='Строки')),
                ('header_fields', models.JSONField(blank=True, default=list, verbose_name='Поля шапки')),
                ('header_rows', models.JSONField(blank=True, default=list, verbose_name='Строки шапки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='accounts.trainingperiod', verbose_name='Период')),
            ],
            options={
                'verbose_name': 'Таблица подготовки',
                'verbose_name_plural': 'Таблицы подготовки',
                'ordering': ('period',),
            },
        ),
        migrations.CreateModel(
            name='TrainingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='ID раздела')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='accounts.trainingsection', verbose_name='Родительский раздел')),
            ],
            options={
                'verbose_name': 'Раздел подготовки',
                'verbose_name_plural': 'Разделы подготовки',
                'ordering': ('parent_id', 'order', 'title'),
            },
        ),
        migrations.AddField(
            model_name='trainingperiod',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='accounts.trainingsection', verbose_name='Раздел'),
        ),
        migrations.AddConstraint(
            model_name='trainingperiod',
            constraint=models.UniqueConstraint(fields=('section', 'slug'), name='unique_training_period_per_section'),
        ),
    ]
