# Generated by Django 4.2.30 on 2026-06-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_seed_combat_training_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodicalManualSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название предмета')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Предмет усулдук колдонмолор',
                'verbose_name_plural': 'Предметы усулдук колдонмолор',
                'ordering': ('order', 'title'),
            },
        ),
    ]
