# Generated by Django 4.2.30 on 2026-07-03 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_update_command_thematic_account_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombatTrainingJournalSection',
            fields=[
            ],
            options={
                'verbose_name': 'Күжүрмөн даярдоону каттоо журналы',
                'verbose_name_plural': 'Күжүрмөн даярдоону каттоо журналы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.trainingsection',),
        ),
    ]
