# Generated by Django 4.2.30 on 2026-07-03 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_combattrainingjournalsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombatTrainingJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_id', models.CharField(max_length=255, unique=True, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название')),
                ('year', models.CharField(blank=True, max_length=40, verbose_name='Окуу жылы')),
                ('unit_name', models.CharField(blank=True, max_length=255, verbose_name='Бөлүкчөнүн аталышы')),
                ('scope', models.CharField(blank=True, max_length=255, verbose_name='Область')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combat_training_journals', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журналы',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
