# Generated by Django 4.2.30 on 2026-07-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_combattrainingjournal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combattrainingjournal',
            options={'ordering': ('-created_at', '-id'), 'verbose_name': 'Күжүрмөн даярдоону каттоо журналы', 'verbose_name_plural': 'Күжүрмөн даярдоону каттоо журналы'},
        ),
        migrations.AlterModelOptions(
            name='combattrainingjournalsection',
            options={'verbose_name': 'Шаблон раздела күжүрмөн даярдоо', 'verbose_name_plural': 'Шаблон раздела күжүрмөн даярдоо'},
        ),
    ]
