# Generated by Django 4.2.30 on 2026-07-09 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_combattrainingjournal_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, verbose_name='Сообщение')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='chat/attachments/', verbose_name='Вложение')),
                ('attachment_kind', models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('file', 'File')], default='', max_length=20, verbose_name='Тип вложения')),
                ('attachment_name', models.CharField(blank=True, max_length=255, verbose_name='Имя вложения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages_received', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages_sent', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение чата с администратором',
                'verbose_name_plural': 'Сообщения чата с администратором',
                'ordering': ('created_at', 'id'),
            },
        ),
    ]
