# Generated by Django 4.2.30 on 2026-09-15 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_alter_submissioneditrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodicalmanualsubject',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.methodicalmanualsubject', verbose_name='Раздел'),
        ),
    ]
