from django.urls import path

from .dashboard_views import (
    AdminDashboardView,
    CombatTrainingJournalDetailView,
    CombatTrainingJournalListCreateView,
    CombatTrainingPlanDetailView,
    CombatTrainingPlanListCreateView,
    CombatTrainingNewsDetailView,
    CombatTrainingNewsLikeView,
    CombatTrainingNewsListCreateView,
    CombatTrainingNewsReadAllView,
    CombatTrainingNewsUnreadCountView,
    LessonSchedulePeriodListCreateView,
    LessonSchedulePeriodDetailView,
    LibraryPeriodDetailView,
    LibraryPeriodListCreateView,
    MethodicalManualDocumentDetailView,
    MethodicalManualDocumentListCreateView,
    MethodicalManualSubjectDetailView,
    MethodicalManualSubjectListCreateView,
    OutpostDashboardView,
    RegionalDashboardView,
    SubmissionEditRequestCreateView,
    SubmissionEditRequestDecisionView,
    SubmissionEditRequestListView,
    ThematicAccountSubmissionListCreateView,
    ThematicAccountSubmissionDetailView,
    ThematicAccountSubmissionForwardView,
)

urlpatterns = [
    path("admin/", AdminDashboardView.as_view(), name="dashboard-admin"),
    path("regional/", RegionalDashboardView.as_view(), name="dashboard-regional"),
    path("outpost/", OutpostDashboardView.as_view(), name="dashboard-outpost"),
    path(
        "combat-training-plans/",
        CombatTrainingPlanListCreateView.as_view(),
        name="combat-training-plan-list",
    ),
    path(
        "combat-training-plans/<int:pk>/",
        CombatTrainingPlanDetailView.as_view(),
        name="combat-training-plan-detail",
    ),
    path(
        "thematic-account-submissions/",
        ThematicAccountSubmissionListCreateView.as_view(),
        name="thematic-account-submission-list",
    ),
    path(
        "thematic-account-submissions/<int:pk>/",
        ThematicAccountSubmissionDetailView.as_view(),
        name="thematic-account-submission-detail",
    ),
    path(
        "thematic-account-submissions/<int:pk>/forward/",
        ThematicAccountSubmissionForwardView.as_view(),
        name="thematic-account-submission-forward",
    ),
    path("thematic-account-submissions/<int:pk>/edit-request/", SubmissionEditRequestCreateView.as_view(), name="submission-edit-request-create"),
    path("submission-edit-requests/", SubmissionEditRequestListView.as_view(), name="submission-edit-request-list"),
    path("submission-edit-requests/<int:pk>/", SubmissionEditRequestDecisionView.as_view(), name="submission-edit-request-decision"),
    path(
        "lesson-schedule-periods/<slug:section_slug>/<str:period_slug>/",
        LessonSchedulePeriodDetailView.as_view(),
        name="lesson-schedule-period-detail",
    ),
    path(
        "methodical-subjects/",
        MethodicalManualSubjectListCreateView.as_view(),
        name="methodical-subject-list",
    ),
    path(
        "methodical-subjects/<int:pk>/",
        MethodicalManualSubjectDetailView.as_view(),
        name="methodical-subject-detail",
    ),
    path(
        "methodical-subjects/<int:subject_pk>/documents/",
        MethodicalManualDocumentListCreateView.as_view(),
        name="methodical-document-list",
    ),
    path(
        "methodical-subjects/<int:subject_pk>/documents/<int:pk>/",
        MethodicalManualDocumentDetailView.as_view(),
        name="methodical-document-detail",
    ),
    path(
        "combat-training-journals/",
        CombatTrainingJournalListCreateView.as_view(),
        name="combat-training-journal-list",
    ),
    path(
        "combat-training-news/",
        CombatTrainingNewsListCreateView.as_view(),
        name="combat-training-news-list",
    ),
    path(
        "combat-training-news/unread-count/",
        CombatTrainingNewsUnreadCountView.as_view(),
        name="combat-training-news-unread-count",
    ),
    path(
        "combat-training-news/read-all/",
        CombatTrainingNewsReadAllView.as_view(),
        name="combat-training-news-read-all",
    ),
    path(
        "combat-training-news/<int:pk>/",
        CombatTrainingNewsDetailView.as_view(),
        name="combat-training-news-detail",
    ),
    path(
        "combat-training-news/<int:pk>/like/",
        CombatTrainingNewsLikeView.as_view(),
        name="combat-training-news-like",
    ),
    path(
        "combat-training-journals/<int:pk>/",
        CombatTrainingJournalDetailView.as_view(),
        name="combat-training-journal-detail",
    ),
    path(
        "lesson-schedule-periods/",
        LessonSchedulePeriodListCreateView.as_view(),
        name="lesson-schedule-period-list",
    ),
    path(
        "library-periods/",
        LibraryPeriodListCreateView.as_view(),
        name="library-period-list",
    ),
    path(
        "library-periods/<slug:section_slug>/<str:period_slug>/",
        LibraryPeriodDetailView.as_view(),
        name="library-period-detail",
    ),
]
